### ISSUE TITLE
Obsolete Serilog Sinks

### ISSUE THREAD

**Issue by rbiq** [intuit/QuickBooks-V3-DotNET-SDK#156]
Serilog.Sinks.RollingFile & Serilog.Sinks.Literate are now obsolete according to nuget. If your package no longer depends on them can you please remove them?

**Comment by rbiq** [comment]
![Uploading image.png…]()

**Comment by rbiq** [comment]
![image](https://user-images.githubusercontent.com/18170071/96501514-70758180-121e-11eb-989d-b31ec353c31b.png)

**Comment by nimisha84** [comment]
Thanks, I will remove them in next release

**Comment by paulduran** [comment]
@nimisha84 On a related note, I think there's a whole heap of serilog dependencies in this SDK that are unnecessary, for example  `Serilog.Sinks.AzureDocumentDB` - these are being dragged into projects that utilise the `IppDotNetSdkForQuickBooksApiV3` nuget package.

**Comment by MatthewSteeples** [comment]
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/pull/139 - I had a go at removing DocumentDb a while ago

**Comment by nimisha84** [comment]
Fixed in 14.4.4.0 release

**Comment by r-work** [comment]
Package is still referencing Serilog, am I missing something here?

![ref](https://user-images.githubusercontent.com/68378520/99786541-8aa0c900-2b16-11eb-8f0b-2bc4b1cfca4a.png)

**Comment by nimisha84** [comment]
Hi,

Serilog.Sinks.RollingFile, Serilog.Sinks.Literate and Serilog.Sinks.AzureDocumentDB were removed. Please see this issue for more details -https://github.com/intuit/QuickBooks-V3-DotNET-SDK/issues/156

Thanks,
Nimisha

**Comment by r-work** [comment]
@nimisha84 **Intuit.Ipp.Core.dll** still references Serilog.Sinks.RollingFile and Serilog.Sinks.Literate, and Android project compile without explicitly referencing them as well.

![ref2](https://user-images.githubusercontent.com/68378520/99947654-35f88a80-2d70-11eb-9eab-c684df0971ec.png)

**Comment by nimisha84** [comment]
Hi Ramya,

Please create a P3 bug to remove the below unwanted serilog dependencies in the next quarterly release.

Thanks for bringing this up r-work.

Thanks,
Nimisha

**Comment by nimisha84** [comment]
All these issues were fixed in 14.6.0.0.

**Comment by hamiltonOC** [comment]
Hello, 

I am using version 14.6.0.0 and still receiving this error with identifying lines redacted. Please let me know if there is any other information required. 

`Could not load type 'Serilog.ConsoleLoggerConfigurationExtensions' from assembly 'Serilog.Sinks.Debug, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
System.TypeLoadException: Could not load type 'Serilog.ConsoleLoggerConfigurationExtensions' from assembly 'Serilog.Sinks.Debug, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
   at Intuit.Ipp.OAuth2PlatformClient.OAuthAdvancedLogging..ctor(Boolean enableSerilogRequestResponseLoggingForDebug, Boolean enableSerilogRequestResponseLoggingForTrace, Boolean enableSerilogRequestResponseLoggingForConsole, Boolean enableSerilogRequestResponseLoggingForFile, String serviceRequestLoggingLocationForFile)
   at Intuit.Ipp.OAuth2PlatformClient.LogHelper.GetAdvancedLogging(Boolean enableSerilogRequestResponseLoggingForDebug, Boolean enableSerilogRequestResponseLoggingForTrace, Boolean enableSerilogRequestResponseLoggingForConsole, Boolean enableSerilogRequestResponseLoggingForFile, String serviceRequestLoggingLocationForFile)
   at Intuit.Ipp.OAuth2PlatformClient.OAuth2Client.RefreshTokenAsync(String refreshToken, Object extra, CancellationToken cancellationToken)`

**Comment by Megaventory** [comment]
@hamiltonOC, see this: https://github.com/intuit/QuickBooks-V3-DotNET-SDK/issues/179. You need to downgrade the specific serilog package or -this is what we did- fork the repo, remove all instances of the serilog packages and build locally and reference your own dll.

**Comment by nimisha84** [comment]
Or try unistalling the SDK, deleting bin folder and doing a clean build.
Check your csproj if it has some ref of this serilog dependency by any chance. Clean that up too.

**Comment by hamiltonOC** [comment]
I was able to remove usage of the project temporarily. Removing the bin and rebuilding did not fix it. I am hoping the issue is resolved before I need this dependency again.

**Comment by nimisha84** [comment]
Sure, will do a fix next upcoming release in about 3-4 weeks time

**Comment by apavelm** [comment]
I faced the same issue and updated SDK to 14.6.0.0, but it didn't help. Uninstall/Install and manual cleaning the solution folder either.

**Comment by nimisha84** [comment]
We will verify n  fix the issue in the next release of the Sdk that is in 2-3 weeks from now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by apavelm** [comment]
Thank you, waiting for a fix. As 14.4.X and 14.6.X version doesn't work with the same error.

**Comment by rajendradewaninet** [comment]
I am also facing the same issue. I am using 14.6.X. When can we expect a fix?

**Comment by nimisha84** [comment]
Fixed in 14.6.1 release
